Reuse request session in CF client.
Without this change, I got these errors after crawling few submissions:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='codeforces.com', port=443):
Max retries exceeded with url: /contest/932/submission/72052331
(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1116c9860>:
Failed to establish a new connection: [Errno 60] Operation timed out'))
```

This change would also improve performance.